[package]
name = "wasm-serde-toml"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_core = { workspace = true }
toml = { workspace = true }
wasm-serde = { path = ".." }
