[package]
name = "wasm-serde-cbor"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_cbor = { workspace = true }
serde_core = { workspace = true }
wasm-serde = { path = ".." }
