[package]
name = "wasm-serde-json"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_bytes = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasm-serde = { path = ".." }
